# Generated by Django 5.2.7 on 2025-10-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_catalogo_estado_alter_producto_catalogo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=15),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('dado_de_baja', 'Dado de Baja'), ('en_reparacion', 'En Reparación'), ('vendido', 'Vendido')], default='disponible', max_length=15),
        ),
    ]
