# Generated by Django 5.2.6 on 2025-11-10 23:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_add_cart_item'),
        ('ventas', '0003_alter_detalleventa_cantidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Cart ya existe, solo creamos CartItem
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.Cart')),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Catalogo')),
            ],
            options={
                'verbose_name': 'Item del Carrito',
                'verbose_name_plural': 'Items del Carrito',
                'db_table': 'ventas_cart_item',
                'unique_together': {('cart', 'catalogo')},
            },
        ),
    ]
